#Author: mudethula_venkateshwarlu@optum.com
Feature: Current Enrollee: Plan Check Negative Formulary Q, Product Negative Formulary Change N and PA TB X
  As a RxClaim User I want to submit a TB claims

  @TC01
  Scenario Outline: Submit a Precondition TB claims in RxClaim for Previous Year and Submit a Main TB claims in RxClaim for Current Year
    #NDC_MultipleList-CENRL
    #Submit a Precondition TB claims in RxClaim for Previous Year
    Given I am on RxClaim PlanAdministrator Menu
    When I create Member with PA "<CarrierID>","<AccountID>","<GroupID>","<MemberID>","<FirstName>","<LastName>","<DOB>","<FromDate>","<ThruDate>"
    Then Validate PA Member "<MemberID>" added
    When I create PA Number "<PANumber>","<Type>","<PAOTC>","<NDCGPIList>","<From>","<Thru>","<Agent>","<Reason>","<IgnoreDrugStatus>"
    And Update Member PA Override and NDC Details "<PAOverrideTB>","<QualQuantity>","<MinQuantity>","<MaxQuantity>","<QualDailyDose>","<MinDailyDose>","<MaxDailyDose>","<PTDQuantityType>","<PTDQuantityDays>","<PTDQuantityMax>","<PTDDaysSupplyType>","<PTDDaysSupplyMin>","<PTDDaysSupplyMax>","<PTD4thQtrDSType>","<PTD4thQtrDSDays>","<PTD4thQtrDSMax>","<QtyDSComp>"
    And Update Plan Drug Status and Turnoff NDC Options "<PlanCode>"
    When I submit a claim with "<BIN1>","<ProcCtrl1>","<Group1>","<PharmacyID1>","<RxNo1>","<Refill1>","<FillDate1>","<MemberID1>","<ProductID1>","<DspQty1>","<DS1>","<PSC1>","<Cost1>"
    Then Validate Claim Status is "P"
    #Scenario Outline: Submit a Main TB claims in RxClaim for Current Year
    And I am on RxClaim PlanAdministrator Menu
    And Update Plan Process Qualifier and Drug Status and Turnon NDC Options "<PlanCodeCY>","<CheckNegFormChangeonProductCY1L>","<NDCListCY1L>", "<ProcessQualifierCY1L>","<ProductIDCY1L>","<QualQuantityCY1L>","<MinQuantityCY1L>","<MaxQuantityCY1L>","<QualDailyDoseCY1L>","<MinDailyDoseCY1L>","<MaxDailyDoseCY1L>","<PTDQuantityTypeCY1L>","<PTDQuantityDaysCY1L>","<PTDQuantityMaxCY1L>","<PTDDaysSupplyTypeCY1L>","<PTDDaysSupplyMinCY1L>","<PTDDaysSupplyMaxCY1L>","<PTD4thQtrDSTypeCY1L>","<PTD4thQtrDSDaysCY1L>","<PTD4thQtrDSMaxCY1L>","<QtyDSCompCY1L>","<NegativeFormularyChangeCY1L>","<MinMaxQuantityCY1L>","<MinMaxDailyDoseCY1L>","<QuantityDaySupplyPTDCY1L>"
    And Update Plan Process Qualifier and Drug Status and Turnon NDC Options "<PlanCodeCY>","<CheckNegFormChangeonProductCY2L>","<NDCListCY2L>", "<ProcessQualifierCY2L>","<ProductIDCY2L>","<QualQuantityCY2L>","<MinQuantityCY2L>","<MaxQuantityCY2L>","<QualDailyDoseCY2L>","<MinDailyDoseCY2L>","<MaxDailyDoseCY2L>","<PTDQuantityTypeCY2L>","<PTDQuantityDaysCY2L>","<PTDQuantityMaxCY2L>","<PTDDaysSupplyTypeCY2L>","<PTDDaysSupplyMinCY2L>","<PTDDaysSupplyMaxCY2L>","<PTD4thQtrDSTypeCY2L>","<PTD4thQtrDSDaysCY2L>","<PTD4thQtrDSMaxCY2L>","<QtyDSCompCY2L>","<NegativeFormularyChangeCY2L>","<MinMaxQuantityCY2L>","<MinMaxDailyDoseCY2L>","<QuantityDaySupplyPTDCY2L>"
	  When I submit a claim with "<BIN2>","<ProcCtrl2>","<Group2>","<PharmacyID2>","<RxNo2>","<Refill2>","<FillDate2>","<MemberID2>","<ProductID2>","<DspQty2>","<DS2>","<PSC2>","<Cost2>"
    Then Validate Claim Status is "<ClaimStatus>"
    #And Validate Claim Reject Code "76 569"
    And Validate PA Number and TB fields "<PANumberCY>","<TBOverrideCY>","<TBPriorDrugStsCY>","<TBRejectReason1CY>","<TBRejectReason2CY>","<TBRejectReason3CY>","<TBPlanEditCY>","<TBPassPreQualifCheckCY>"

    Examples: 
      | CarrierID | AccountID  | GroupID        | MemberID | FirstName | LastName | DOB      | FromDate | ThruDate | PANumber | Type | PAOTC | NDCGPIList  | From  | Thru  | Agent | Reason | IgnoreDrugStatus | PAOverrideTB | QualQuantity | MinQuantity | MaxQuantity | QualDailyDose | MinDailyDose | MaxDailyDose | PTDQuantityType | PTDQuantityDays | PTDQuantityMax | PTDDaysSupplyType | PTDDaysSupplyMin | PTDDaysSupplyMax | PTD4thQtrDSType | PTD4thQtrDSDays | PTD4thQtrDSMax | QtyDSComp | PlanCode   | BIN1   | ProcCtrl1 | Group1 | PharmacyID1 | RxNo1        | Refill1 | FillDate1 | MemberID1 | ProductID1  | DspQty1 | DS1 | PSC1 | Cost1 | PlanCodeCY | CheckNegFormChangeonProductCY1L | NDCListCY1L | ProcessQualifierCY1L | NDCListCY2 | ProcessQualifierCY2 | ProductIDCY1L | QualQuantityCY1L | MinQuantityCY1L | MaxQuantityCY1L | QualDailyDoseCY1L | MinDailyDoseCY1L | MaxDailyDoseCY1L | PTDQuantityTypeCY1L | PTDQuantityDaysCY1L | PTDQuantityMaxCY1L | PTDDaysSupplyTypeCY1L | PTDDaysSupplyMinCY1L | PTDDaysSupplyMaxCY1L | PTD4thQtrDSTypeCY1L | PTD4thQtrDSDaysCY1L | PTD4thQtrDSMaxCY1L | QtyDSCompCY1L | NegativeFormularyChangeCY1L | MinMaxQuantityCY1L | MinMaxDailyDoseCY1L | QuantityDaySupplyPTDCY1L | BIN2   | ProcCtrl2 | Group2 | PharmacyID2 | RxNo2        | Refill2 | FillDate2 | MemberID2 | ProductID2  | DspQty2 | DS2 | PSC2 | Cost2 | PANumberCY | TBOverrideCY | TBPriorDrugStsCY | TBRejectReason1CY | TBRejectReason2CY | TBRejectReason3CY | TBPlanEditCY | TBPassPreQualifCheckCY | ClaimStatus |
      | KSID3419C | KSID3419CA | KSID3419SAMPLE |          | AUTOMEM   | AUTOMEM  | 12251987 |    10101 |   123139 | 12345678 | N    | *     | 33358021001 | 10118 | 13018 | O     | AA     | N                | X            |              |             |             |               |              |              | Y               |                 |             10 | Y                 |                  |               10 |                 |                 |                | H         | KSID3419GE | 922552 |    922552 | *      | APHARM      | 765488397613 |      00 |    122217 |           | 33358021001 |      10 |  10 |    0 |   100 | KSID3419GE | Q                               | KSIDL1      | P                    | KSIDL2     | P                   |   33358021001 |                  |                 |                 |                   |                  |                  | Y                   |                     |                 15 | Y                     |                      |                   15 |                     |                     |                    | H             | N                           | N                  | N                   | T                        | 922552 | *         | *      | APHARM      | 765488397613 |      00 |     10118 |           | 33358021001 |      20 |  20 |    0 |   100 |   12345678 | KSIDTB       |                  | CENRL             | CENRL             | CENRL             |              | N                      | R           |
