#Author: mudethula_venkateshwarlu@optum.com
Feature: Current Enrollee: Plan Check Negative Formulary Q, Product Negative Formulary Change N and PA TB X
  As a RxClaim User I want to submit a TB claims

  @TC01
  Scenario Outline: Submit a Precondition TB claims in RxClaim for Previous Year and Submit a Main TB claims in RxClaim for Current Year
    #NDC - NENRL
    #Submit a Precondition TB claims in RxClaim for Previous Year
    Given I am on RxClaim PlanAdministrator Menu
    When I create Member with PA "<CarrierID>","<AccountID>","<GroupID>","<MemberID>","<FirstName>","<LastName>","<DOB>","<FromDate>","<ThruDate>"
    Then Validate PA Member "<MemberID>" added
    When I create PA Number "<PANumber>","<Type>","<PAOTC>","<NDCGPIList>","<From>","<Thru>","<Agent>","<Reason>","<IgnoreDrugStatus>"
    And Update Member PA Override and NDC Details "<PAOverrideTB>","<QualQuantity>","<MinQuantity>","<MaxQuantity>","<QualDailyDose>","<MinDailyDose>","<MaxDailyDose>","<PTDQuantityType>","<PTDQuantityDays>","<PTDQuantityMax>","<PTDDaysSupplyType>","<PTDDaysSupplyMin>","<PTDDaysSupplyMax>","<PTD4thQtrDSType>","<PTD4thQtrDSDays>","<PTD4thQtrDSMax>","<QtyDSComp>"
    #And Update Plan Drug Status and Turnoff NDC Options "<PlanCode>"
    #When I submit a claim with "<BIN1>","<ProcCtrl1>","<Group1>","<PharmacyID1>","<RxNo1>","<Refill1>","<FillDate1>","<MemberID1>","<ProductID1>","<DspQty1>","<DS1>","<PSC1>","<Cost1>"
    #Then Validate Claim Status is "P"
    #Scenario Outline: Submit a Main TB claims in RxClaim for Current Year
    And I am on RxClaim PlanAdministrator Menu
    #And Update Plan Drug Status and Turnon NDC Options "<PlanCodeCY>","<CheckNegFormChangeonProductCY>","<ProductIDCY>","<QualQuantityCY>","<MinQuantityCY>","<MaxQuantityCY>","<QualDailyDoseCY>","<MinDailyDoseCY>","<MaxDailyDoseCY>","<PTDQuantityTypeCY>","<PTDQuantityDaysCY>","<PTDQuantityMaxCY>","<PTDDaysSupplyTypeCY>","<PTDDaysSupplyMinCY>","<PTDDaysSupplyMaxCY>","<PTD4thQtrDSTypeCY>","<PTD4thQtrDSDaysCY>","<PTD4thQtrDSMaxCY>","<QtyDSCompCY>","<NegativeFormularyChangeCY>","<MinMaxQuantityCY>","<MinMaxDailyDoseCY>","<QuantityDaySupplyPTDCY>"
    And Update Plan Drug Status and Turnon NDC Options for Medicaid "<PlanCodeCY>","<CheckNegFormChangeonProductCY>","<ProductIDCY>","<QualQuantityCY>","<MinQuantityCY>","<MaxQuantityCY>","<QualDailyDoseCY>","<MinDailyDoseCY>","<MaxDailyDoseCY>","<PTDQuantityTypeCY>","<PTDQuantityDaysCY>","<PTDQuantityMaxCY>","<PTDDaysSupplyTypeCY>","<PTDDaysSupplyMinCY>","<PTDDaysSupplyMaxCY>","<PTD4thQtrDSTypeCY>","<PTD4thQtrDSDaysCY>","<PTD4thQtrDSMaxCY>","<QtyDSCompCY>","<NegativeFormularyChangeCY>","<MinMaxQuantityCY>","<MinMaxDailyDoseCY>","<QuantityDaySupplyPTDCY>"
    When I submit a claim with "<BIN2>","<ProcCtrl2>","<Group2>","<PharmacyID2>","<RxNo2>","<Refill2>","<FillDate2>","<MemberID2>","<ProductID2>","<DspQty2>","<DS2>","<PSC2>","<Cost2>"
    Then Validate Claim Status is "<ClaimStatus>"
    #And Validate Claim Reject Code "76 569"
    And Validate PA Number and TB fields "<PANumberCY>","<TBOverrideCY>","<TBPriorDrugStsCY>","<TBRejectReason1CY>","<TBRejectReason2CY>","<TBRejectReason3CY>","<TBPlanEditCY>","<TBPassPreQualifCheckCY>"

    Examples: 
      | CarrierID | AccountID  | GroupID        | MemberID | FirstName | LastName | DOB      | FromDate | ThruDate | PANumber | Type | PAOTC | NDCGPIList  | From   | Thru   | Agent | Reason | IgnoreDrugStatus | PAOverrideTB | QualQuantity | MinQuantity | MaxQuantity | QualDailyDose | MinDailyDose | MaxDailyDose | PTDQuantityType | PTDQuantityDays | PTDQuantityMax | PTDDaysSupplyType | PTDDaysSupplyMin | PTDDaysSupplyMax | PTD4thQtrDSType | PTD4thQtrDSDays | PTD4thQtrDSMax | QtyDSComp | PlanCodeCY | CheckNegFormChangeonProductCY | ProductIDCY | QualQuantityCY | MinQuantityCY | MaxQuantityCY | QualDailyDoseCY | MinDailyDoseCY | MaxDailyDoseCY | PTDQuantityTypeCY | PTDQuantityDaysCY | PTDQuantityMaxCY | PTDDaysSupplyTypeCY | PTDDaysSupplyMinCY | PTDDaysSupplyMaxCY | PTD4thQtrDSTypeCY | PTD4thQtrDSDaysCY | PTD4thQtrDSMaxCY | QtyDSCompCY | NegativeFormularyChangeCY | MinMaxQuantityCY | MinMaxDailyDoseCY | QuantityDaySupplyPTDCY | BIN2   | ProcCtrl2 | Group2 | PharmacyID2 | RxNo2        | Refill2 | FillDate2 | MemberID2 | ProductID2  | DspQty2 | DS2 | PSC2 | Cost2 | PANumberCY | TBOverrideCY | TBPriorDrugStsCY | TBRejectReason1CY | TBRejectReason2CY | TBRejectReason3CY | TBPlanEditCY | TBPassPreQualifCheckCY | ClaimStatus |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | Y                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | N                         | N                | Y                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  | QTYLT             | NENRL             |                   |              | Y                      | P           |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | Y                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | Y                         | N                | Y                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  | QTYLT             | NENRL             |                   |              | Y                      | P           |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | Y                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | N                         | N                | N                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  |                   |                   |                   |              | Y                      | R           |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | Y                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | Y                         | N                | N                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  |                   |                   |                   |              | Y                      | R           |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | N                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | N                         | N                | Y                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  | QTYLT             | NENRL             |                   |              | Y                      | P           |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | N                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | Y                         | N                | Y                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  | QTYLT             | NENRL             |                   |              | Y                      | P           |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | N                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | N                         | N                | N                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  |                   |                   |                   |              | Y                      | R           |
      | KSID3419C | KSID3419CA | KSID3419CAG016 |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | KSID341915 | N                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | Y                         | N                | N                 | N                      | 922552 |    922552 | *      | APHARM      | 7.65488E+11  |      00 |    010118 |           | 33358021001 |      40 |  10 |    0 |   100 |   12345678 | KSIDTB       |                  |                   |                   |                   |              | Y                      | R           |
      #Max DD
      #| VMCAR29   | VMACC29    | VMGRP002       |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | 3419AUTO04 | Q                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | N                         | N                | Y                 | N                      | 939393 | *         | *      | APHARM      | 765488397613 |      00 |    010118 |           | 33358021001 |      80 |  20 |    0 |   100 |   12345678 | KSIDTB       |                  | NENRL             |                   |                   |              | N                      | P           |
      #| VMCAR29   | VMACC29    | VMGRP002       |          | AUTOMEM   | AUTOMEM  | 12251987 |   010118 |   123139 | 12345678 | N    | *     | 33358021001 | 010118 | 010518 | O     | AA     | N                | X            |              |             |             | S             |              |            3 |                 |                 |                |                   |                  |                  |                 |                 |                |           | 3419AUTO04 | Q                             | 33358021001 |                |               |               | S               |                |              2 |                   |                   |                  |                     |                    |                    |                   |                   |                  |             | Y                         | N                | Y                 | N                      | 939393 | *         | *      | APHARM      | 765488397613 |      00 |    010118 |           | 33358021001 |      80 |  20 |    0 |   100 |   12345678 | KSIDTB       |                  | NENRL             |                   |                   |              | Y                      | P           |
